const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_ERROR = 'SET_ERROR';
const REMOVE_ERROR = 'REMOVE_ERROR';

export {
  GET_MEASUREMENTS,
  LOGIN,
  LOGOUT,
  SET_USER_DATA,
  SET_ERROR,
  REMOVE_ERROR,
};
