const BASE = 'https://guarded-sands-43543.herokuapp.com/';
const SIGN_UP_USER = 'SIGN_UP_USER';
const LOGIN_USER = 'LOGIN_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const LOGIN_USER_SESSION = 'LOGIN_USER_SESSION';
const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_ERROR = 'SET_ERROR';
const REMOVE_ERROR = 'REMOVE_ERROR';

export {
  GET_MEASUREMENTS,
  LOGIN,
  LOGOUT,
  SET_USER_DATA,
  SET_ERROR,
  REMOVE_ERROR,
  BASE,
  LOGIN_USER,
  LOGIN_USER_FAILURE,
  SIGN_UP_USER,
  SIGNUP_USER_FAILURE,
  LOGOUT_USER,
  LOGIN_USER_SESSION,
};
